Student_name = input("sandhya")
Student_age = int(input(18))
Course_rating = float(input(7.8))
print(f"Student: {Student_name}")
print(f"Age: {Student_age}")
print(f"Rating: {Course_rating}")
print(type(Student_name))
print(type(Student_age))
print(type(Course_rating))